### ISSUE TITLE
big tps and fps lag

### ISSUE THREAD

**Issue by Foxyas** [LtxProgrammer/Changed-Minecraft-Mod#292] opened 2023-02-17 19:59 UTC
![ALOT FO TPS PROBLEMS](https://user-images.githubusercontent.com/119010731/219779360-d6c656b1-2902-4b36-b0b1-996061f3a1f3.png)
and if you use more than 2 render blocks then game will have big fpt lag and lag

**Comment by LtxProgrammer** [comment] 2023-02-17 22:05
Duplicate of #284

**Closed by LtxProgrammer** 2023-02-17 22:05 UTC
