### ISSUE TITLE
latex sharks overloading server

### ISSUE THREAD

**Issue by MechaWarrior** [LtxProgrammer/Changed-Minecraft-Mod#35] opened 2022-11-21 22:01 UTC
[crash-2022-11-21_21.57.10-server.txt](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/files/10060915/crash-2022-11-21_21.57.10-server.txt)

**Comment by MechaWarrior** [comment] 2022-11-23 00:41
could this by chance get fixed with a hotfix update? as it's really annoying to have the server crash every 4 minutes.

**Comment by BaiTian6641** [comment] 2022-11-23 05:16
put some command blocks, and let they continually run:
/kill @e[type=changed:latex_shark_male]
/kill @e[type=changed:latex_shark_female]
/kill @e[type=changed:latex_tiger_shark]
Also, turn off command block output by  /gamerule commandBlockOutput false

**Comment by MechaWarrior** [comment] 2022-11-23 05:37
> put some command blocks, and let they continually run: /kill @e[type=changed:latex_shark_male] /kill @e[type=changed:latex_shark_female] /kill @e[type=changed:latex_tiger_shark] Also, turn off command block output by /gamerule commandBlockOutput false

ive even installed a mod on the server that stops them from spawning thing is it still crashes i think either because some players have shark form and the crash changes to abstractlatex

**Comment by BaiTian6641** [comment] 2022-11-23 05:58
I think we need suspend shark and orca form before bug fix.

**Comment by LtxProgrammer** [comment] 2022-11-23 17:00
I cannot confirm this is from the Changed mod

**Comment by LtxProgrammer** [comment] 2022-11-23 17:17
Closing issue as cannot reproduce; reopen when you have effective steps to reproduce

**Closed by LtxProgrammer** 2022-11-23 17:17 UTC
Labels: bug
