### ISSUE TITLE
Latex mobs can phase through lab doors (When they are closed on them)

### ISSUE THREAD

**Issue by bijimio** [LtxProgrammer/Changed-Minecraft-Mod#16] opened 2022-11-06 04:31 UTC

**Comment by LtxProgrammer** [comment] 2022-11-06 13:46
This needs instructions for replication. I can't prove this bug exists

**Comment by LtxProgrammer** [comment] 2022-11-08 03:45
Bug is from closing doors on latex creatures. Not a bug, but may be interesting to damage entities when they get a door closed on them.

**Closed** 2022-12-15 18:39 UTC
Labels: enhancement
