### ISSUE TITLE
Better Com bat compatability issue

### ISSUE THREAD

**Issue by Lexinyxia** [LtxProgrammer/Changed-Minecraft-Mod#899] opened 2024-05-16 00:45 UTC
Mod models have a weird interaction with the changed mod (and the subsequent "changed addon" which will not be discussed here) and when mid-animation, you are unable to see anything but the face of the transfur you have become. the animations work just fine, but the models act strange when interacting with them.

**Comment by Lexinyxia** [comment] 2024-05-16 19:38
it's an issue from 0.13.1. I downloaded the mod and am using it in a private modpack with friends and we have been going out of our way to add multiple mods that infected players can use since better combat does the weird rendering issue.

**Comment by LtxProgrammer** [comment] 2024-05-17 05:29
Duplicate of #869. Already fixed/added for 0.14.

**Closed** 2024-05-17 05:30 UTC
