### ISSUE TITLE
Creative Mode Issues (Innocuous)

### ISSUE THREAD

**Issue by XiaoTDM** [LtxProgrammer/Changed-Minecraft-Mod#1117] opened 2024-10-22 15:05 UTC
There are a few issues with creative mode at the moment:
1. Pure White still seems to attack the player in certain situations (when there is one be attacked and it is far away from the attacked one, seems to be impossible to fix)

2. The latex arrow will bounce repeatedly when it hits the player.
![image](https://github.com/user-attachments/assets/23fc2e88-a431-402a-be95-92cd1183e1d0)

3.Syringes and flasks will be consumed (a bit inconvenience)

4. Benign can break blocks, but cannot place or use them.

**Comment by XiaoTDM** [comment] 2024-10-22 15:08
Strangely, vanilla arrows don't bounce like this.

**Comment by spacedan228** [comment] 2024-10-28 20:26
1. Already fixed in 0.14
2. some testing is needed, try sending a video here
3. they don't? maybe it is caused by other mods
4. benign latex cannot break blocks or interact with anything really

**Comment by XiaoTDM** [comment] 2024-10-29 14:57
1.Difficult to reproduce.
2.Like the video.
3.That's how they behaved. Recommend that unlimited use be available.
4.Can break but cannot interact. Recommend to relax the restrictions in Creative. (This maybe cause by [Pull #938](https://github.com/LtxProgrammer/Changed-Minecraft-Mod/pull/938))
Tested with Latest GitHub Copy & New-Installed Minecraft Core with only Changed Mod.

https://github.com/user-attachments/assets/8ec93f2c-0877-4290-91ae-b198d93cffb4

**Closed** 2024-11-17 01:52 UTC
