### ISSUE TITLE
Oculus

### ISSUE THREAD

**Issue by cecnull1** [LtxProgrammer/Changed-Minecraft-Mod#1040] opened 2024-09-16 11:30 UTC
[crash-2024-09-16_19.24.30-client.txt](https://github.com/user-attachments/files/17012070/crash-2024-09-16_19.24.30-client.txt)

[crash-2024-09-15_10.20.54-client.txt](https://github.com/user-attachments/files/17012082/crash-2024-09-15_10.20.54-client.txt)

**Comment by LtxProgrammer** [comment] 2024-09-17 02:55
Duplicate of #1036

**Closed by LtxProgrammer** 2024-09-17 02:55 UTC
