### ISSUE TITLE
MCA Reborn overrides hand texture 

### ISSUE THREAD

**Issue by S0ME0NE03** [LtxProgrammer/Changed-Minecraft-Mod#353] opened 2023-03-17 01:15 UTC
![2023-03-16_18 14 49](https://user-images.githubusercontent.com/128107137/225787245-ecf67362-44ca-4cd8-a0c1-4d9a1c4f3490.png)

**Comment by LtxProgrammer** [comment] 2023-03-17 02:01
Won't fix. This is not an issue caused by the Changed: Minecraft Mod

**Closed by LtxProgrammer** 2023-03-17 02:01 UTC
